---
#
# Set facts to use in verification function
#
- set_fact:
    device_path: '/dev/mapper/fedora-root'

- set_fact:
    disks: ['vdc']

- set_fact:
    lvm_vg: 'fedora'

- set_fact:
    device_name: 'root'

- set_fact:
    fs_type: 'ext4'

#
# Run the verification functions
#
- name: Verify the previously run role results (present)
  include_tasks: "verify-present-mount.yml"
  when: state == "present"

- name: Verify the previously run role results (absent)
  include_tasks: "verify-absent-mount.yml"
  when: state == "absent"
