---

- name: Read the /etc/fstab file
  shell: cat /etc/fstab
  register: fstab_buf
  when: state == "present"

- name: Verify that device_path is in /etc/fstab file
  assert:
    that: fstab_buf.stdout.find(device_path) != -1
    msg: "{{ device_path }} is not present in /etc/fstab file."
  when: device_type == "lvm" and state == "present"

- name: Verify that specified disk is in /etc/fstab file
  assert:
    that: fstab_buf.stdout.find(disks[0]) != -1
    msg: "{{ disks[0] }} is not present in /etc/fstab file."
  when: device_type == "disk" and state == "present"
